name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: "nixpkgs=./nix"
      - name: "Run tests"
        run: |
          nix-shell shell.nix --run "echo OK"
          nix-shell shell.nix --run 'elixir --version'
          nix-shell shell.nix --run 'mix hex.info'
